camel:
  server-port: ${PORT:5000}
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true


zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 8
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
  broker:
    contactpoint: "127.0.0.1:26500"

cloud:
  aws:
    bucket-name: ${AWS_BUCKET_NAME:paymenthub-ee-dev}
    enabled: true
    credentials:
      access-key: ${AWS_ACCESS_KEY:access_key_from_aws}
      secret-key: ${AWS_SECRET_KEY:secret_key_from_aws}
    region:
      static: us-east-2
    stack:
      auto: false

slcb:
  auth:
    host: https://g2p-test.slcb.com:8443
    auth-endpoint: /api/auth
    username: ${SLCB_USERNAME:username}
    password: ${SLCB_PASSWORD:password}
  api:
    host: https://g2p-test.slcb.com:8443
    transaction-request-endpoint: /api/transactionRequest
    reconciliation-endpoint: /reconciliation
    account-balance-endpoint: /accountBalance
  signature:
    key: ${SLCB_SIGNATURE_KEY:very_long_string}
  account:
    number: "003001003879112168"
    type: 0
  institutionCode: "SLCB"

config:
  date-format: "yyyy-MM-dd'T'hh:mm:ssXXX"
  reconciliation:
    enable: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

dfspids: "DFSPID"
